name: Build LaTeX document
on: [push,pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Tree All project
        run: sudo apt install tree;tree

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
